<a href="https://colab.research.google.com/github/pramodkumhal/Python_Libraries_Learning/blob/main/NumPy_Files/NumPy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Arithmethic Function

In [ ]:
import numpy as np
var=np.array([1,4,9,25])
print("minimum: ",np.min(var),np.argmin(var))
print("maximum: ",np.max(var),np.argmax(var))
print("Sqrt: ",np.sqrt(var))

minimum:  1 0
maximum:  25 3
Sqrt:  [1. 2. 3. 5.]


In [ ]:
var1=np.array([[2,1,3],[9,5,6]])
print(np.min(var1,0),np.argmin(var1))

[2 1 3] 1


In [ ]:
var=np.array([1,2,3,4])
print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1  3  6 10]
