<a href="https://colab.research.google.com/github/pramodkumhal/Python_Libraries_Learning/blob/main/NumPy_Files/NumPy9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Join and Split Array

Join Array

In [ ]:
#1D Array
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([5,6,7,8])
arr1=np.concatenate((var1,var2))
print(arr1)

[1 2 3 4 5 6 7 8]


In [ ]:
#2D Array
import numpy as np
varr1=np.array([[1,2],[3,4]])
varr2=np.array([[5,6],[7,8]])
arr2=np.concatenate((varr1,varr2),axis=1)
print(arr2)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#1D Array using stack
import numpy as np
var_1=np.array([1,2,3,4])
var_2=np.array([5,6,7,8])
arr=np.stack((var_1,var_2))  #axis=0
print(arr)
print("\n")
arr_1=np.stack((var_1,var_2),axis=1)
print(arr_1)
print("\n")
arr_2=np.hstack((var_1,var_2))   #row
print(arr_2)
print("\n")
arr_3=np.vstack((var_1,var_2))  #column
print(arr_3)
print("\n")
arr_4=np.dstack((var_1,var_2))   #height
print(arr_4)

[[1 2 3 4]
 [5 6 7 8]]


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


[1 2 3 4 5 6 7 8]


[[1 2 3 4]
 [5 6 7 8]]


[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


Split Array

In [ ]:
#1D Array
import numpy as np
var=np.array([1,2,3,4,5,6])
print(var)
print("\n")
ar=np.array_split(var,3)
print(ar)
print(ar[1])

[1 2 3 4 5 6]


[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [ ]:
#2D Array
import numpy as np
var2=np.array([[1,2],[4,5],[6,7]])
print(var2)
print("\n")
ar1=np.array_split(var2,3)
ar2=np.array_split(var2,3,axis=1)
print(ar1)
print('\n')
print(ar2)

[[1 2]
 [4 5]
 [6 7]]


[array([[1, 2]]), array([[4, 5]]), array([[6, 7]])]


[array([[1],
       [4],
       [6]]), array([[2],
       [5],
       [7]]), array([], shape=(3, 0), dtype=int64)]


#Search Array

In [ ]:
import numpy as np
var=np.array([5,6,2,1,4,8,9,6,2])
# index       0,1,2,3,4,5,6,7,8
x=np.where(var==2)
print(x)

(array([2, 8]),)


In [ ]:
import numpy as np
var1=np.array([1,2,3,4,5,6,7,8,9,10,11])
# index       0,1,2,3,4,5,6
x1=np.searchsorted(var1, 4)
print(x1)

var_1=np.array([1,2,3,4,5,6,7,8,9,10,11])
# index       0,1,2,3,4,5,6
x2=np.searchsorted(var_1, 5,side="right")
print(x2)

x3=np.searchsorted(var_1, 5,side="left")
print(x3)

3
5
4


In [ ]:
import numpy as np
var1=np.array([1,2,3,4,9,10,11])
# index       0,1,2,3,4,5,6
x=np.searchsorted(var1,[5,6,7],side="right")
print(x)


[4 4 4]


Sort

In [ ]:
var1=np.array([1,2,3,4,9,10,11])
# index       0,1,2,3,4,5,6
print(np.sort(var1))

[ 1  2  3  4  9  9 10 11]


In [ ]:
var1=np.array(['a','r','v','c','u'])
# index       0,1,2,3,4,5,6
print(np.sort(var1))

['a' 'c' 'r' 'u' 'v']


In [ ]:
#sort 2 D array
var1=np.array([[3,2],[6,5],[9,10]])
# index       0,1,2,3,4,5,6
print(np.sort(var1))

[[ 2  3]
 [ 5  6]
 [ 9 10]]


Filter Array

In [ ]:
var3=np.array(['r','v','c','u'])
f=[True,False,False,True]
new = var3[f]
print(new)
print(type(new))


['r' 'u']
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

# Create a NumPy array of integers
arr = np.array([10, 15, 20, 25, 30])
filtered_arr = arr[arr>20]
print(filtered_arr)


[25 30]


#Shuffle

In [ ]:
import numpy as np
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[1 5 3 4 2]


#unique()

In [ ]:
import numpy as np
var1=np.array([1,7,2,3,4,5,6,2,1,4,3,6])
x=np.unique(var1,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 2, 3, 4, 5, 6, 1]), array([2, 2, 2, 2, 1, 2, 1]))


#resize()

In [ ]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


#flatten() and ravel()

In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print("flatten :",a.flatten(order='F'))
print("Ravel :",np.ravel(a,order='C'))

[[1 2]
 [3 4]
 [5 6]]
flatten : [1 3 5 2 4 6]
Ravel : [1 2 3 4 5 6]


#insert()

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
# index       0 1 2 3
print(var)
v=np.insert(var,2,10)
print(v)


[1 2 3 4]
[ 1  2 10  3  4]


In [ ]:
#2D Array
var1=np.array([[1,2,3],[4,5,6]])
v1=np.insert(var1,2,[2,3],axis=1)
print(v1)

[[1 2 2 3]
 [4 5 3 6]]


#delete()

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
# index       0 1 2 3
print(var)
v=np.delete(var,2)
print(v)

[1 2 3 4]
[1 2 4]


#Matrix

In [ ]:
import numpy as np
var1=np.matrix([[1,2],[4,5]])
var2=np.matrix([[1,2],[4,5]])
print(var1)
print(type(var1))
print(var1*var2)
print()
print(var1.dot(var2))

[[1 2]
 [4 5]]
<class 'numpy.matrix'>
[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]


#Matrix Function in Numpy Array

**transpose(), swapaxes(), inverse ,power, determinate**





In [ ]:
import numpy as np
var=np.matrix([[1,2],[3,4]])
print(var,"\n")
#transpose
print(np.transpose(var))
print()
print(var.T) #transpose
print()
#swapaxes
print(np.swapaxes(var,0,1))
print()
#inverse
print(np.linalg.inv(var))
print()
#power
print(var**2)
print()
print(np.linalg.matrix_power(var,2))
print()
#determinate
print(np.linalg.det(var))

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]

-2.0000000000000004
