<a href="https://colab.research.google.com/github/pramodkumhal/Python_Libraries_Learning/blob/main/NumPy_Files/NumPy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Type


In [ ]:
#integer
import numpy as np
var=np.array([1,2,3,4])
print("Data Type:",var.dtype)

Data Type: int64


In [ ]:
#float
import numpy as np
var=np.array([1.1,2.8,3.6,4.6])
print("Data Type:",var.dtype)

Data Type: float64


In [ ]:
#string
import numpy as np
var=np.array(['A','B','C','D'])
print("Data Type:",var.dtype)

Data Type: <U21


In [ ]:
#mix string have high precedence than integer
import numpy as np
var=np.array(['A','B','C','D',1,2,3,4])
print("Data Type:",var.dtype)

Data Type: <U21


In [ ]:
#changing int64 into int8
x=np.array([1,2,3,4],dtype=np.int8)
print("Data Type:",x.dtype)
print(x)

Data Type: int8
[1 2 3 4]


In [ ]:
#changing data types of numpy array from int to float
x=np.array([1,2,3,4],dtype='f')
print("Data Type:",x.dtype)
print(x)

Data Type: float32
[1. 2. 3. 4.]


In [ ]:
x=np.array([1,2,3,4])
new=np.float32(x)
print("Data Type:",x.dtype)
print(x)
print("Data Type:",new.dtype)
print(new)

Data Type: int64
[1 2 3 4]
Data Type: float32
[1. 2. 3. 4.]


In [ ]:
x=np.array([1,2,3,4])
new=x.astype(np.float32)
print(x)
print(new)

[1 2 3 4]
[1. 2. 3. 4.]
