<a href="https://colab.research.google.com/github/pramodkumhal/Python_Libraries_Learning/blob/main/NumPy_Files/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy array with Random number

In [ ]:
#Randon Rand()
import numpy as np
var1=np.random.rand(4)
print(var1)

[0.29919379 0.38645829 0.22215314 0.28820255]


In [ ]:
#Randon Randn()
import numpy as np
var2=np.random.randn(4)
print(var2)

[-0.10371825  0.6692088   0.45734968  0.43781822]


In [ ]:
#Randon Ranf()
import numpy as np
var3=np.random.ranf(4)
print(var3)

[0.47564283 0.42640162 0.08927074 0.3855639 ]


In [ ]:
#Randon Randint()
import numpy as np
var4=np.random.randint(1,10,size=(4,3))
print(var4)

[[4 9 7]
 [1 4 9]
 [4 8 7]
 [2 8 5]]
