<a href="https://colab.research.google.com/github/pramodkumhal/Python_Libraries_Learning/blob/main/NumPy_Files/NumPy6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Shape and Reshaping in NumPy Array

In [ ]:
import numpy as np
var=np.array([[1,2],[1,2]])
print(var,"\n")
print(var.shape)

[[1 2]
 [1 2]] 

(2, 2)


In [ ]:
var1= np.array([1,2,3,4],ndmin=2)
print(var1)
print(var1.ndim)
print(var1.shape)

[[1 2 3 4]]
2
(1, 4)


#Reshape

In [ ]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=var2.reshape(3,2,2)
print(x)
print(x.ndim)
print("\n")
#new=x.reshape(-1)
new=x.ravel()
print(new,new.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


[ 1  2  3  4  5  6  7  8  9 10 11 12] 1
