<a href="https://colab.research.google.com/github/pramodkumhal/Python_Libraries_Learning/blob/main/NumPy_Files/NumPy8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Indexing NumPy Array

In [ ]:
#1D Array
import numpy as np
var=np.array([1,2,3])
print(var[1])

2


In [ ]:
#2D Array
import numpy as np
var=np.array([[1,2],[3,4]])
print(var[1,0])

3


In [ ]:
#3D Array
import numpy as np
var=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(var[1,1,0])

7


#Slicing Numpy Array

In [ ]:
var=np.array([1,2,3,4,5])
print(var[:2])

[1 2]


In [ ]:
import numpy as np
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var,"\n")
print(var[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2]
 [5]]


#Iteration NumPy ARray

In [ ]:
import numpy as np
var=np.array([4,5,6,7])
print(var,"\n")
for i in var:
  print(i)

[4 5 6 7] 

4
5
6
7


In [ ]:
import numpy as np
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var,"\n")
for i in var:
  print(i)
print("\n")
for k in var:
  for j in k:
    print(j)

[[1 2 3 4]
 [5 6 7 8]] 

[1 2 3 4]
[5 6 7 8]


1
2
3
4
5
6
7
8


In [ ]:
import numpy as np
var=np.array([[[1,2,3,4],[8,6,2,4]]])
print(var,"\n")
for i in var:
  for j in i:
    for k in j:
      print(k)

[[[1 2 3 4]
  [8 6 2 4]]] 

1
2
3
4
8
6
2
4


In [ ]:
import numpy as np
var=np.array([[[4,5,6,7],[5,6,2,4]]])
print(var,"\n")
for i in np.nditer(var):
  print(i)

[[[4 5 6 7]
  [5 6 2 4]]] 

4
5
6
7
5
6
2
4


In [ ]:
import numpy as np
var=np.array([[[4,5,6,7],[5,6,2,4]]])
print(var,"\n")
for i,d in np.ndenumerate(var):
  print(i,d)

[[[4 5 6 7]
  [5 6 2 4]]] 

(0, 0, 0) 4
(0, 0, 1) 5
(0, 0, 2) 6
(0, 0, 3) 7
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 2
(0, 1, 3) 4
