<a href="https://colab.research.google.com/github/pramodkumhal/Python_Libraries_Learning/blob/main/NumPy_Files/NumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy Learning**

#Array

In [ ]:
import numpy as np
x=[1,2,3,4]
y=np.array([1,2,3,4,5])
print(y)

[1 2 3 4 5]


In [ ]:
l=[]
for i in range(1,5):
  int_1=int(input("enter:"))
  l.append(int_1)
print(np.array(l))

enter:12
enter:13
enter:14
enter:15
[12 13 14 15]


In [ ]:
import numpy as np
y=np.array([1,2,3,4])
print(y)
print("dimension of :",y.ndim)

import numpy as np
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)
print("dimension of :",y.ndim)
print(y.shape)

import numpy as np
y=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(y)
print(y.shape)
print("dimension of :",y.ndim)


[1 2 3 4]
dimension of : 1
[[1 2 3 4]
 [5 6 7 8]]
dimension of : 2
(2, 4)
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
(1, 3, 4)
dimension of : 3


In [ ]:
a=np.array([1,2,3,4],ndmin=10)
print(a)
print(a.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


#Numpy Array using Numpy Function

In [ ]:
#zero
ar_zero = np.zeros((2))
print(ar_zero)
#one
ar_one = np.ones(2)
print(ar_one)
#empty
ar_empty = np.empty((2))
print(ar_empty)
#range
ar_rn=np.arange(1,4,2)
print(ar_rn)
#eye
ar_dia=np.eye(3,5)
print(ar_dia)

[0. 0.]
[1. 1.]
[1. 1.]
[1 3]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
ar_line=np.linspace(1,50,num=50,endpoint=False, retstep=False, dtype=None)
print(ar_line)

NameError: name 'np' is not defined